var fullName = 'Tai Doan';
var isCool = false;
var totalPets = 2;
console.log('fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
console.log('isCool:', isCool);
console.log('typeof isCool:', typeof isCool);
console.log('totalPets:', totalPets);
console.log('typeof totalPets:', typeof totalPets);
var unknown = null;
console.log('unknown:', unknown);
console.log('typeof unknown:', typeof unknown);
var never;
console.log('never:', never);
console.log('typeof never:', typeof never);
